name: Build with flakes: fortanix-sgx-tools & sgxs-tools

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_fortanix-sgx-tools:
    runs-on: ubuntu-latest
    env:
      elf2sgxs_hash: "411d70e17634d6ad54dcc7dbf40f61fab5dfc9626fd8120ce9fd2063561f44d5"
      runner_hash: "c5437c2bd13fbe2806ea51fd4c97e993d848ee86960302888b33319065e1a38c"
      runner_cargo_hash: "a4775959992cb69ceb943c5374d54dbe077912763dbb9ff324f35a16f1a8d531"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install nix from cachix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/9a3cfff2f9035ca0bd54ff13b608c4492eca6be3.tar.gz
      - run: nix --version
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build fortanix-sgx-tools/

      # TODO: Implement action to check the hash
      - name: Shasum check ftxsgx-elf2sgxs
        run: |
          echo "$elf2sgxs_hash *result/bin/ftxsgx-elf2sgxs" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check ftxsgx-runner
        run: |
          echo "$runner_hash *result/bin/ftxsgx-runner" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check ftxsgx-runner-cargo
        run: |
          echo "$runner_cargo_hash *result/bin/ftxsgx-runner-cargo" | \
            shasum --algorithm 512256 --binary --strict --check

  build_sgxs-tools:
    runs-on: ubuntu-latest
    env:
      sgx_detect: "843e854afb0865b890ce2f1fda3d24f87d1104885879f6fa3ad4557e9531f36b"
      sgxs_append: "40fa7879924abdb5d72392b71aa3d19e048ea51a089c1ed4fa1da3609b998352"
      sgxs_build: "710947acf207a1c6c885e13a1adb7c6c0bfc47f6733762d23527ada4d531675f"
      sgxs_info: "c1548b4e2ee1140eaf85b5240aa86790caeb4c86a80921ae4d5e2e9ec5bcecb1"
      sgxs_load: "0bdf2c3bc4bd438878bad6d19a3513dfd1239359290d974988a10b941796fb17"
      sgxs_sign: "76fb3bffe8427b8b12b0721cd6ab1e9a0601ce5d463d86c2f3ab4cb160c9466c"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install nix from cachix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/9a3cfff2f9035ca0bd54ff13b608c4492eca6be3.tar.gz
      - run: nix --version
      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: initc3
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build sgxs-tools/

      # TODO: Implement action to check the hash
      - name: Shasum check sgxs-detect
        run: |
          echo "$sgx_detect *result/bin/sgx-detect" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check sgxs-append
        run: |
          echo "$sgxs_append *result/bin/sgxs-append" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check sgxs-build
        run: |
          echo "$sgxs_build *result/bin/sgxs-build" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check sgxs-info
        run: |
          echo "$sgxs_info *result/bin/sgxs-info" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check sgxs-load
        run: |
          echo "$sgxs_load *result/bin/sgxs-load" | \
            shasum --algorithm 512256 --binary --strict --check
      - name: Shasum check sgxs-sign
        run: |
          echo "$sgxs_sign *result/bin/sgxs-sign" | \
            shasum --algorithm 512256 --binary --strict --check
